version: '3.9'

services:
  api:
    build: './api'
    container_name: api
    ports:
      - '3001:3001'
    networks:
      - rede

  front:
    build: './front'
    container_name: front
    ports:
      - '3000:3000'
    networks:
      - rede

  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste_pratico
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rede

volumes:
  pgdata:

networks:
  rede:
    driver: bridge
